# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config.py', '.'),
        ('api.txt', '.'),
        ('knowledge', 'knowledge'),
    ],
    hiddenimports=[
        'models', 'models.coin',
        'vision', 'vision.screen_capture', 'vision.gemini_analyzer',
        'physics', 'physics.engine', 'physics.simulator',
        'solver', 'solver.optimizer', 'solver.strategy',
        'solver.fast_sim', 'solver.mcts_engine', 'solver.gpu_physics',
        'ui', 'ui.overlay',
        'ai', 'ai.auto_tuner', 'ai.feedback_loop',
        'utils', 'utils.coordinate_mapper', 'utils.state_detector',
        'pymunk', 'pymunk.autogeometry', 'pymunk.constraint',
        'pymunk.body', 'pymunk.shape', 'pymunk.space',
        'mss', 'mss.windows',
        'pygetwindow', 'pygetwindow._pygetwindow_win',
        'google.genai', 'google.generativeai',
        'PIL', 'PIL.Image',
        'numpy', 'cv2', 'tkinter',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['pyi_rth_utf8.py'],
    excludes=[
        'torch', 'torchvision', 'torchaudio',
        'PyQt6', 'PyQt5', 'PySide6', 'PySide2',
        'matplotlib', 'scipy', 'pandas',
        'IPython', 'jupyter', 'notebook',
        'transformers', 'tensorflow', 'keras',
        'sklearn', 'scikit-learn', 'sympy', 'wx',
        'fugashi', 'websockets',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CoinGameAssistant',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
